In [1]:
import numpy as np

n1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
n2 = np.array([[10, 11, 12, 13],[14, 15, 16, 17]])

In [2]:
n3 = np.vstack([n1, n2])
n3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [3]:
np.hstack([n1, n2])

array([[ 1,  2,  3,  4, 10, 11, 12, 13],
       [ 5,  6,  7,  8, 14, 15, 16, 17]])

In [4]:
np.column_stack([n1, n2])

array([[ 1,  2,  3,  4, 10, 11, 12, 13],
       [ 5,  6,  7,  8, 14, 15, 16, 17]])

In [7]:
ar2 = np.arange(0, 6)
ar3 = np.arange(7, 13)
ar4 = np.vstack([ar2, ar3])
ar4

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
ar5 = np.hstack([ar2, ar3])
ar5

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12])

In [9]:
ar6 = np.column_stack([ar2, ar3])
ar6

array([[ 0,  7],
       [ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12]])

In [11]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
arr1.shape[1]

4

In [18]:
for i in range(arr1.shape[0]):
    for j in range(arr1.shape[1]):
        if arr1[i, j] <10:
            arr1[i, j] = 0

            
arr1
        

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
arr1

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
arr = np.arange(1,26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
aq = arr[[3,0], [2,4]]
aq


array([18,  5])

In [75]:
import pandas as pd

df = pd.DataFrame(np.arange(0, 25).reshape(5, 5),index= ["row1","row2","row3","row4","row5"], columns=["a", "b", "c", "d", "e"])
#df.set_index([["row1","row2","row3","row4","row5"]], inplace= True)
#df.set_columns([["a", "b", "c", "d", "e"]])
#df.reset_index(level= None,drop=True,inplace= True)
df


a   b   c   d   e
row1   0   1   2   3   4
row2   5   6   7   8   9
row3  10  11  12  13  14
row4  15  16  17  18  19
row5  20  21  22  23  24

In [54]:
df.loc[3, "d"]

d    18
Name: 3, dtype: int32

In [61]:
df.iloc[[0,3,0],[0,2,4]]

a   c   e
0   0   2   4
3  15  17  19
0   0   2   4

In [58]:
#convert df to array
arr = df.values
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
type(arr)

numpy.ndarray

In [60]:
arr[[0, 3, 0],[0, 2, 4]]

array([ 0, 17,  4])

In [62]:
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [87]:
jibon = df.loc[['row1',"row2", "row3"],"c":"d"].values.shape
jibon

(3, 2)

In [88]:
df

a   b   c   d   e
row1   0   1   2   3   4
row2   5   6   7   8   9
row3  10  11  12  13  14
row4  15  16  17  18  19
row5  20  21  22  23  24

In [99]:
df["a"].value_counts()

15    1
5     1
20    1
10    1
0     1
Name: a, dtype: int64

In [100]:
df

a   b   c   d   e
row1   0   1   2   3   4
row2   5   6   7   8   9
row3  10  11  12  13  14
row4  15  16  17  18  19
row5  20  21  22  23  24

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 5 columns):
a    5 non-null int32
b    5 non-null int32
c    5 non-null int32
d    5 non-null int32
e    5 non-null int32
dtypes: int32(5)
memory usage: 300.0+ bytes


In [103]:
df.describe()

a          b          c          d          e
count   5.000000   5.000000   5.000000   5.000000   5.000000
mean   10.000000  11.000000  12.000000  13.000000  14.000000
std     7.905694   7.905694   7.905694   7.905694   7.905694
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000   9.000000
50%    10.000000  11.000000  12.000000  13.000000  14.000000
75%    15.000000  16.000000  17.000000  18.000000  19.000000
max    20.000000  21.000000  22.000000  23.000000  24.000000

In [126]:
from io import StringIO, BytesIO
ami = ("col1, col2, col3\n"
      "x, y, z\n"
      "a, b, c\n")
#ami
pd.read_csv(StringIO(ami))

col1  col2  col3
0    x     y     z
1    a     b     c